### ISSUE TITLE
redis wrapper fails

### ISSUE THREAD

**Issue by rtodea** [strongloop/strong-agent#10]
See issue described here: https://github.com/Automattic/kue/issues/953.

For what we understood, when calculating the args of the Redis commands, if the command is passed without a callback, the string, `function() {}`, is introduced.

I will add steps to reproduce.

**Comment by bnoordhuis** [comment]
Hi @rtodea, thanks for the bug report.  With what version of strong-agent and the redis module are you seeing that?  If it's redis@>=2.6.0, can you upgrade to strong-agent@2.1.0?

**Comment by sam-github** [comment]
`npm install -g strongloop` just installed strong-agent@2.1.0 for me, so either it has a problem with latest redis, or the user is using an older verion.

@rtodea did you install using `npm install -g strongloop`? If so, can you give us the output of `npm ls -g strong-agent` please?

**Comment by sam-github** [comment]
@bnoordhuis comment https://github.com/strongloop/strongloop/issues/323#issuecomment-257159799 indicates that strong-agent@2.0.4  works with redis, and while they didn't say, since 2.1.0 is what gets installed as a dependency when either strong-pm is installed, or strongloop is installed, its possible we have a regression in redis between 2.0.4 and 2.1.0

@rtodea can you give a repro? I'm not familiar with kue, if you had some runnable code that triggers this, it should be reasonably straight forward to fix.

**Comment by rtodea** [comment]
@sam-github, @bnoordhuis please see this repo: https://github.com/rtodea/strong-agent-issue-10 for steps to reproduce.

@sam-github, installing **2.0.4** solves the problem, so it might be a regression.
These are the versions provided via `./node_modules/.bin/slc -v`:
```
strongloop v6.0.3 (node v6.5.0)
├── strong-arc@1.8.9 (3dd25ac)
├── strong-build@2.1.2 (a98f310)
├── strong-deploy@3.1.4 (9b29df0)
├── strong-mesh-models@8.1.0 (62e539b)
├── strong-pm@5.2.3
├── strong-registry@1.1.6 (f8c2339)
├── strong-start@1.3.4 (28c261d)
├─┬ strong-supervisor@3.3.3
│ └── strong-agent@2.1.0 (1767f27)
├── generator-loopback@1.24.4 (0c6b9c3)
├── node-inspector@0.7.4
└── nodefly-register@0.3.3
```

Redis version:
```
redis@2.6.3
```
If you need any more info, I will gladly provide.

**Comment by bnoordhuis** [comment]
@rtodea Thanks for the test case, much appreciated!  I was able to reproduce and will have a fix ready shortly.

**Comment by sam-github** [comment]
strong-agent 2.1.1 should fix this, please reinstall `strongloop`, or `strong-pm`, whichever you are using.
